name: DeltaBluesEventDesign
favicon: null
layout_spectrum: 0.5467507839202881
typography_spectrum: 0.712391100358218
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4895628485828638
  lightness: 0.74155711568892
  saturation: 0.220431640278548
  rhythmicContrast: 0.5292678868863732
purpose: []
